
name: Manual workflow to delete labels in bulk

on: 
  workflow_dispatch:
    inputs:
      labels:
        description: a single or comma separated list of labels to delete
        required: true
        type: string

jobs:
  delete-labels:
    name: Delete Labels
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Default Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
      - name: Run Label Action
        uses: ./.github/actions/delete-labels
        with:
          labels: ${{ inputs.labels }}
