name: Apply labels in bulk

on: 
  workflow_dispatch:
    inputs:
      issues:
        description: a single or comma separated list of issue numbers
        required: true
        type: string
      labels:
        description: a single or comma separated list of labels to apply to all listed issues
        required: true
        type: string
      colors:
        description: |
          A single or comma separated list of colors to create the labels with if needed.
          the list order is the same as `labels`. Missing or blank values (e.g. `FFFFFF,,FFFFFF`) use the `default_color`
        type: string
      default-color:
        description: default color to create labels with
        default: "#D4C5F9"
        type: string
  
jobs:
  apply-labels:
    name: Apply Labels
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Default Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
      - name: Run Label Action
        uses: ./.github/actions/add-labels
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          issues: ${{ inputs.issues }}
          labels: ${{ inputs.labels }}
          colors: ${{ inputs.colors }}
          default-color: ${{ inputs.default-color }}
