name: Build Application

on:
  push:
    branches-ignore:
      - "renovate/**"
    paths:
      # File types
      - "**.cpp"
      - "**.h"
      - "**.java"

      # Directories
      - "buildconfig/"
      - "cmake/"
      - "launcher/"
      - "libraries/"
      - "program_info/"
      - "tests/"

      # Files
      - "CMakeLists.txt"
      - "COPYING.md"

      # Workflows
      - ".github/workflows/build.yml"
      - ".github/workflows/trigger_builds.yml"
  pull_request:
    paths:
      # File types
      - "**.cpp"
      - "**.h"

      # Directories
      - "buildconfig/"
      - "cmake/"
      - "launcher/"
      - "libraries/"
      - "program_info/"
      - "tests/"

      # Files
      - "CMakeLists.txt"
      - "COPYING.md"

      # Workflows
      - ".github/workflows/build.yml"
      - ".github/workflows/trigger_builds.yml"
  workflow_dispatch:

jobs:
  build_debug:
    name: Build Debug
    uses: ./.github/workflows/build.yml
    with:
      build-type: Debug
    secrets: inherit
